package cs3500.pa03.controller;

import static org.junit.jupiter.api.Assertions.assertEquals;

import cs3500.pa03.model.ShipType;
import java.io.IOException;
import java.io.StringReader;
import java.util.HashMap;
import java.util.Random;
import org.junit.jupiter.api.Test;

class ManualVsAutoControllerTest {


  @Test
  public void testPlayGame() throws IOException {
    String input = "\n6 6\nplayer one\n"
        + "0 1 1 1\n"
        + "1 0 1 1\n"
        + "0 1 1 1\n"
        + "1 1 0 1\n"
        + "1 1 1 0\n"
        + "5 5 5 5\n"
        + "\n1\n 1\n 1\n 1\n"
        + "-1\n 0\n4\n 0\n1\n 1\n4\n 1\n"
        + "1\n 0\n4\n 0\n1\n 1\n4\n 1\n"
        + "5\n 1\n1\n 2\n3\n 2\n4\n 2\n"
        + "5\n 2\n1\n 3\n3\n 3\n4\n 3\n"
        + "5\n 3\n1\n 4\n3\n 4\n4\n 4\n"
        + "2\n 5\n3\n 5\n4\n 5\n5\n 5\n";
    StringReader stringReader = new StringReader(input);
    String output = "Hello! Welcome to the OOD BattleSalvo Game!\n"
        + "Please enter a valid height and width below:\n"
        + "Please enter your name\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Please enter your fleet in the order\n"
        + "[Carrier, Battleship, Destroyer, Submarine].\n"
        + "Remember, your fleet may not exceed size " + 6 + ".\n"
        + "Your fleet must of one of each ship type\n"
        + "Opponent Board:\n"
        + "000000\n"
        + "000000\n"
        + "000000\n"
        + "000000\n"
        + "000000\n"
        + "000000\n\n"
        + "Your Board:\n"
        + "SSSS00\n"
        + "000000\n"
        + "000SSS\n"
        + "0SSSSS\n"
        + "000000\n"
        + "SSSSSS\n\n"
        + "Top left corner is origin (0, 0).\nPlease enter " + 4 + " shots:\n"
        + "Top left corner is origin (0, 0).\nPlease enter " + 4 + " shots:\n"
        + "Opponent Board:\n"
        + "0H00H0\n"
        + "0H00H0\n"
        + "000000\n"
        + "000000\n"
        + "000000\n"
        + "000000\n\n"
        + "Your Board:\n"
        + "SSSS00\n"
        + "000M00\n"
        + "000SSS\n"
        + "0SSSHH\n"
        + "M00000\n"
        + "SSSSSS\n\n"
        + "Top left corner is origin (0, 0).\nPlease enter " + 4 + " shots:\n"
        + "Opponent Board:\n"
        + "0H00H0\n"
        + "0H00HH\n"
        + "0H0HH0\n"
        + "000000\n"
        + "000000\n"
        + "000000\n\n"
        + "Your Board:\n"
        + "SSSS00\n"
        + "M00M00\n"
        + "000SSH\n"
        + "0SSSHH\n"
        + "M00M00\n"
        + "SSSHSS\n\n"
        + "Top left corner is origin (0, 0).\nPlease enter " + 4 + " shots:\n"
        + "Opponent Board:\n"
        + "0H00H0\n"
        + "0H00HH\n"
        + "0H0HHH\n"
        + "0H0HH0\n"
        + "000000\n"
        + "000000\n\n"
        + "Your Board:\n"
        + "SSSS00\n"
        + "M00M00\n"
        + "000SHH\n"
        + "0HSHHH\n"
        + "M0MM00\n"
        + "SSSHSS\n\n"
        + "Top left corner is origin (0, 0).\nPlease enter " + 4 + " shots:\n"
        + "Opponent Board:\n"
        + "0H00H0\n"
        + "0H00HH\n"
        + "0H0HHH\n"
        + "0H0HHH\n"
        + "0H0HH0\n"
        + "000000\n\n"
        + "Your Board:\n"
        + "HSSS00\n"
        + "M00M00\n"
        + "000HHH\n"
        + "0HSHHH\n"
        + "M0MM00\n"
        + "SSSHSS\n\n"
        + "Top left corner is origin (0, 0).\nPlease enter 3 shots:\n"
        + "Opponent Board:\n"
        + "0H00H0\n"
        + "0H00HH\n"
        + "0H0HHH\n"
        + "0H0HHH\n"
        + "0H0HH0\n"
        + "00MHH0\n\n"
        + "Your Board:\n"
        + "HSSS00\n"
        + "M00M00\n"
        + "000HHH\n"
        + "0HSHHH\n"
        + "M0MM00\n"
        + "SSSHSS\n\n"
        + "Game Over. You won!";
    StringBuilder actualOutput = new StringBuilder();
    ManualVsAutoController mvac =
        new ManualVsAutoController(stringReader, actualOutput, new Random(1), new Random(2));
    mvac.playGame();
    assertEquals(output, actualOutput.toString());
  }


}